/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2f3133',
        'surface-tint': '#476553',
        'on-secondary-fixed': '#261a00',
        'on-primary-fixed-variant': '#2f4d3c',
        'on-surface-variant': '#424843',
        secondary: '#795900',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#c9ebd3',
        'surface-variant': '#e2e2e5',
        primary: '#000000',
        tertiary: '#000000',
        surface: '#f9f9fc',
        'status-success': '#0B733B',
        outline: '#727973',
        'status-info': '#004B87',
        'on-secondary-container': '#6c5000',
        'on-secondary-fixed-variant': '#5b4300',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e2e2e5',
        'surface-light': '#F8F9FA',
        'primary-container': '#022112',
        'surface-container': '#eeeef0',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#2e121f',
        'primary-fixed-dim': '#adceb8',
        'secondary-container': '#febf0e',
        'surface-subtle': '#E9ECEF',
        'on-primary-fixed': '#022112',
        'on-surface': '#1a1c1e',
        'inverse-primary': '#adceb8',
        'tertiary-container': '#2e121f',
        'tertiary-fixed': '#ffd9e5',
        'on-tertiary-fixed-variant': '#5f3d4a',
        'secondary-fixed': '#ffdf9f',
        'on-background': '#1a1c1e',
        'surface-container-high': '#e8e8ea',
        error: '#ba1a1a',
        'on-primary-container': '#6b8b77',
        'inverse-on-surface': '#f0f0f3',
        'outline-variant': '#c2c8c1',
        'tertiary-fixed-dim': '#e9baca',
        'surface-container-low': '#f3f3f6',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f9f9fc',
        'surface-dim': '#dadadc',
        'secondary-fixed-dim': '#fbbd07',
        background: '#f9f9fc',
        'on-error': '#ffffff',
        'on-tertiary-container': '#a27987',
        'on-error-container': '#93000a',

        // Brand palette derived from the logo: deep green + gold
        brand: {
          green: {
            950: '#02170d',
            900: '#022112',
            800: '#06331d',
            700: '#0b4a2b',
            600: '#166b41',
            500: '#2f8a5a',
            400: '#5aa87c',
            300: '#adceb8',
            200: '#c9ebd3',
            100: '#e3f5e9',
            50: '#f1faf4',
          },
          gold: {
            700: '#5b4300',
            600: '#795900',
            500: '#a37800',
            400: '#d99f00',
            300: '#febf0e',
            200: '#ffd45c',
            100: '#ffdf9f',
            50: '#fff8e6',
          },
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'stack-lg': '32px',
        'container-max': '1280px',
        'margin-desktop': '48px',
        'stack-sm': '8px',
        'section-padding': '80px',
        'stack-md': '16px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': [
          '56px',
          { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-bold': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg-mobile': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      backgroundImage: {
        'brand-grid':
          'linear-gradient(rgba(173,206,184,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(173,206,184,0.08) 1px, transparent 1px)',
      },
      backgroundSize: {
        grid: '48px 48px',
      },
      keyframes: {
        'dash-flow': {
          to: { strokeDashoffset: '-240' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '0.35', transform: 'scale(1)' },
          '50%': { opacity: '0.75', transform: 'scale(1.12)' },
        },
        'drift-slow': {
          '0%, 100%': { transform: 'translate3d(0, 0, 0)' },
          '50%': { transform: 'translate3d(0, -14px, 0)' },
        },
      },
      animation: {
        'dash-flow': 'dash-flow 6s linear infinite',
        'glow-pulse': 'glow-pulse 5s ease-in-out infinite',
        'drift-slow': 'drift-slow 7s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
